[package]
name = "task_scheduler"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "worker"

[[bin]]
name = "scheduler"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
